# Creating a basic Neural Networks
In this notebook I using tensorflow, to create a DNN with subclassing API.

The data is sintetic, only to understand how the library works...

In [1]:
import tensorflow as tf

In [2]:
def sintetic_data(shape:tuple):
    X = tf.random.uniform(shape=shape)
    y= tf.random.normal(shape=shape)
    return X,y 

X_train,y_train = sintetic_data(shape = (100,1))
X_val,y_val = sintetic_data(shape = (20,1))
X_test,y_test = sintetic_data(shape = (10,1))

In [3]:

class BasicModel(tf.keras.Model):
    def __init__(self,units, activation,num_hidden_states,**kwargs):
        super().__init__(**kwargs)
        self.num_hidden_states=num_hidden_states
        self.input_layer = tf.keras.Input(shape=(1,))
        self.dense1 = tf.keras.layers.Dense(units, activation=activation,input_shape = [1])
        self.dense2 = tf.keras.layers.Dense(units, activation=activation)
        self.main_output = tf.keras.layers.Dense(1)
    
    def call(self, inputs):
        dense1 = self.dense1(inputs)
        dense2 = self.dense2(dense1)
        for i in range(self.num_hidden_states - 1):
            dense2 = self.dense2(dense2)
        output = self.main_output(dense2)
        return output
    
model = BasicModel(units=100, activation="relu",num_hidden_states=2)

loss_fn = tf.keras.losses.MeanSquaredError()
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

model.compile(loss=loss_fn,
              optimizer=optimizer,
              metrics=["mae"])
model.fit(X_train,y_train,validation_data=(X_val,y_val),epochs=100,verbose=False)

c:\Users\rafin\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
model.evaluate(X_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.3556 - mae: 0.8486


[1.3556076288223267, 0.8486039042472839]

In [5]:
model.predict(tf.random.uniform(shape=(10,1)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[ 0.0651329 ],
       [-0.04995131],
       [ 0.20862377],
       [ 0.10885155],
       [ 0.24045259],
       [ 0.22787458],
       [ 0.13503286],
       [ 0.21613047],
       [ 0.11613606],
       [ 0.05841366]], dtype=float32)

In [6]:
y_test

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[ 0.97152734],
       [ 0.96739554],
       [ 0.8071222 ],
       [ 0.24184835],
       [-2.534822  ],
       [-0.6249649 ],
       [ 1.8374463 ],
       [ 0.3095532 ],
       [ 0.5578998 ],
       [-0.06731419]], dtype=float32)>