In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.16.1'

# What is a constant and variable tensors

In [5]:
tf.constant(7)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [13]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [14]:
tf.constant([1,2,3]).ndim

1

In [8]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [15]:
tf.constant([[1,2,3],[4,5,6]]).ndim

2

In [11]:
tf.constant([[[[1],[2],[3]]],[[[4],[5],[6]]]])

<tf.Tensor: shape=(2, 1, 3, 1), dtype=int32, numpy=
array([[[[1],
         [2],
         [3]]],


       [[[4],
         [5],
         [6]]]])>

In [16]:
tf.constant([[[[1],[2],[3]]],[[[4],[5],[6]]]]).ndim

4

In [17]:
tf.constant([[[1,2,3],
              [4,5,6]],
             [[1,2,3],
              [4,5,6]]])

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])>

In [18]:
tf.constant([[[1,2,3],
              [4,5,6]],
             [[1,2,3],
              [4,5,6]]]).ndim

3

In [19]:
tf.Variable([[[1,2,3],
              [4,5,6]],
             [[1,2,3],
              [4,5,6]]])

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])>

## Creating random tensors

In [52]:
random_tf = tf.random.Generator.from_seed(42)

In [53]:
random_tf = random_tf.normal(shape =(5,4))
random_tf

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
       [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
       [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085]],
      dtype=float32)>

In [47]:
tf.random.shuffle(random_tf)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ],
       [ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],
      dtype=float32)>

In [54]:
tf.ones(shape=(3,6))

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [55]:
tf.zeros(shape=(3,6))

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Creating a tensor from a csv

I'm taking a personal csv to understand how can i transform a csv in a tensor

In [56]:
import pandas as pd
import numpy as np

In [67]:
df = pd.read_csv('MAC000002.csv')
df.head()

time_idx  Energy_kwh house_hold  temperature  apparentTemperature  \
0         0      43.319  MAC000002         7.01                 3.66   
1         1      37.267  MAC000002         7.49                 4.24   
2         2      33.954  MAC000002         7.16                 3.74   
3         3      30.503  MAC000002         7.04                 3.89   
4         4      26.725  MAC000002         6.29                 3.34   

   bool_weather_missing_values  year  month  day  hour  dayofweek_num  
0                            0  2013      1    1     0              1  
1                            0  2013      1    1     1              1  
2                            0  2013      1    1     2              1  
3                            0  2013      1    1     3              1  
4                            0  2013      1    1     4              1

In [72]:
df = df[['house_hold','time_idx', 'year', 'month', 'day', 'hour', 'temperature',
       'apparentTemperature', 'bool_weather_missing_values','dayofweek_num','Energy_kwh']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10153 entries, 0 to 10152
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   house_hold                   10153 non-null  object 
 1   time_idx                     10153 non-null  int64  
 2   year                         10153 non-null  int64  
 3   month                        10153 non-null  int64  
 4   day                          10153 non-null  int64  
 5   hour                         10153 non-null  int64  
 6   temperature                  10151 non-null  float64
 7   apparentTemperature          10151 non-null  float64
 8   bool_weather_missing_values  10153 non-null  int64  
 9   dayofweek_num                10153 non-null  int64  
 10  Energy_kwh                   10153 non-null  float64
dtypes: float64(3), int64(7), object(1)
memory usage: 872.6+ KB


In [73]:
df = df.iloc[:,1:]

In [74]:
df.head()

time_idx  year  month  day  hour  temperature  apparentTemperature  \
0         0  2013      1    1     0         7.01                 3.66   
1         1  2013      1    1     1         7.49                 4.24   
2         2  2013      1    1     2         7.16                 3.74   
3         3  2013      1    1     3         7.04                 3.89   
4         4  2013      1    1     4         6.29                 3.34   

   bool_weather_missing_values  dayofweek_num  Energy_kwh  
0                            0              1      43.319  
1                            0              1      37.267  
2                            0              1      33.954  
3                            0              1      30.503  
4                            0              1      26.725

In [75]:
df_numpy = df.to_numpy()

In [76]:
df_tensor = tf.Variable(df_numpy)

In [66]:
df_tensor

<tf.Variable 'Variable:0' shape=(10153, 10) dtype=float64, numpy=
array([[0.00000000e+00, 2.01300000e+03, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 4.33190000e+01],
       [1.00000000e+00, 2.01300000e+03, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 3.72669999e+01],
       [2.00000000e+00, 2.01300000e+03, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 3.39540000e+01],
       ...,
       [1.01500000e+04, 2.01400000e+03, 2.00000000e+00, ...,
        0.00000000e+00, 3.00000000e+00, 5.58810000e+01],
       [1.01510000e+04, 2.01400000e+03, 2.00000000e+00, ...,
        0.00000000e+00, 3.00000000e+00, 4.14860001e+01],
       [1.01520000e+04, 2.01400000e+03, 2.00000000e+00, ...,
        0.00000000e+00, 4.00000000e+00, 1.38099999e+01]])>

In [77]:
tf.size(df_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=101530>

In [78]:
df_tensor[0]

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.0000e+00, 2.0130e+03, 1.0000e+00, 1.0000e+00, 0.0000e+00,
       7.0100e+00, 3.6600e+00, 0.0000e+00, 1.0000e+00, 4.3319e+01])>

In [79]:
df_tensor[:,-1]

<tf.Tensor: shape=(10153,), dtype=float64, numpy=
array([43.319    , 37.2669999, 33.954    , ..., 55.881    , 41.4860001,
       13.8099999])>

In [80]:
df_tensor.shape

TensorShape([10153, 10])

In [81]:
df_tensor[:,:-1].shape[0]

10153

In [89]:
tf.expand_dims(df_tensor[:,:-1],axis=0)

<tf.Tensor: shape=(1, 10153, 9), dtype=float64, numpy=
array([[[0.0000e+00, 2.0130e+03, 1.0000e+00, ..., 3.6600e+00,
         0.0000e+00, 1.0000e+00],
        [1.0000e+00, 2.0130e+03, 1.0000e+00, ..., 4.2400e+00,
         0.0000e+00, 1.0000e+00],
        [2.0000e+00, 2.0130e+03, 1.0000e+00, ..., 3.7400e+00,
         0.0000e+00, 1.0000e+00],
        ...,
        [1.0150e+04, 2.0140e+03, 2.0000e+00, ..., 1.4100e+00,
         0.0000e+00, 3.0000e+00],
        [1.0151e+04, 2.0140e+03, 2.0000e+00, ..., 1.4200e+00,
         0.0000e+00, 3.0000e+00],
        [1.0152e+04, 2.0140e+03, 2.0000e+00, ..., 1.4700e+00,
         0.0000e+00, 4.0000e+00]]])>